In [1]:
import numpy as np
import math
import matplotlib.pyplot as plt
import random


Генератор $A$ и $x$ и $f$

In [76]:
n = 3
c = 10

A = c*(np.random.rand(n, n) - 0.5*(np.ones((n,n))))
#A = np.zeros((3,3))
#A[0][1] = 1
#A[1][2] = 4
#A[2][0] = 1

x = c*(np.random.rand(n, 1) - 0.5*(np.ones((n,1))))

#x = np.ones((3,1))

f = A.dot(x)
#f = np.zeros((3, 1))
#f[1][0] = 3

#print(np.sqrt(np.sum((A.dot(x) - f)**2)))

print(A)
print(np.linalg.det(A))
print(x)

print(f)

print("x =", np.linalg.inv(A).dot(f))

[[-2.33381303 -2.0800435  -3.24892498]
 [-3.0403423   0.45413197  2.51152111]
 [ 3.6117075  -4.13209021  1.82272382]]
-92.0338422541083
[[ 2.33597992]
 [-4.57759454]
 [ 3.76427382]]
[[-8.15998785]
 [ 0.27304258]
 [34.21314133]]
x = [[ 2.33597992]
 [-4.57759454]
 [ 3.76427382]]


Метод Якоби

In [77]:
def Iacoby (A, f, x_0, eps):
    x = np.copy(x_0)
    n = np.shape(A)[0]
    
    new_A = np.copy(A)
    new_f = np.copy(f)
    
    print(A)
    
    for i in range(n):
        new_f[i] = new_f[i]/new_A[i][i]
        new_A[i] = new_A[i]/new_A[i][i]

    print(new_A)
    print(np.linalg.det(new_A))
    print(new_f)
        
    new_A -= np.eye(n,n)
    
    
    print(new_A)
    #print(A)
    
    #for i in range(100):
    while (np.sqrt(abs(np.sum((A.dot(x) - f)**2))) > eps):
            #print(np.sqrt(np.sum((A.dot(x) - f)**2)))
            x = new_f - new_A.dot(x)
            #print(x)
    return x

In [78]:
x_ans = Iacoby(A, f, c*np.random.rand(n, 1), 0.001)
#x_ans = Iacoby(A, f, x, 0.001)
#print(np.sqrt(np.sum((A.dot(x) - f)**2)))
#print(np.sqrt(np.sum((A.dot(x_ans) - f)**2)))

print(x_ans)
#print(A.dot(x_ans))
print(x)
#print(A.dot(x))

[[-2.33381303 -2.0800435  -3.24892498]
 [-3.0403423   0.45413197  2.51152111]
 [ 3.6117075  -4.13209021  1.82272382]]
[[ 1.          0.89126398  1.39211022]
 [-6.6948431   1.          5.53037721]
 [ 1.98148916 -2.26698645  1.        ]]
47.64074503400186
[[ 3.49641884]
 [ 0.6012406 ]
 [18.77033752]]
[[ 0.          0.89126398  1.39211022]
 [-6.6948431   0.          5.53037721]
 [ 1.98148916 -2.26698645  0.        ]]
[[-5.46470140e+307]
 [-1.08823688e+307]
 [ 1.12947028e+308]]
[[ 2.33597992]
 [-4.57759454]
 [ 3.76427382]]


C:\Users\nota0\AppData\Local\Temp\ipykernel_91600\716065167.py:25: RuntimeWarning: overflow encountered in square
  while (np.sqrt(abs(np.sum((A.dot(x) - f)**2))) > eps):


Метод зейделя

In [79]:
def Seidel (A, f, x_0, eps):
    x_last = np.copy(x_0)
    x_last[0] = x_last[0] + 2*eps
    x = np.copy(x_0);
    
    n = np.shape(A)[0]
    
    new_A = np.copy(A)
    new_f = np.copy(f)
    
    for i in range(n): 
        if new_A[i][i] == 0:
            for j in range(n):
                if A[j][i] != 0:
                    new_A[i] += A[j]
                    new_f[i] += f[j]
                    break
    
    for i in range(n):
        new_f[i] /= new_A[i][i]
        new_A[i] /= new_A[i][i]

    new_A -= np.eye(n,n)
        
    
    while (np.sqrt(abs(np.sum((x_last - x)**2))) > eps):
        x_last = np.copy(x)
        for i in range(n):
            x[i] = (new_f[i] - new_A[i].dot(x))
        
    return x
        

In [80]:
x_ans = Seidel(A, f, c*np.random.rand(n, 1), 0.001)
#x_ans = Iacoby(A, f, x, 0.001)
print(np.sqrt(np.sum((A.dot(x) - f)**2)))
print(np.sqrt(np.sum((A.dot(x_ans) - f)**2)))

print(x_ans)
#print(A.dot(x_ans))
print(x)
#print(A.dot(x))

0.0
nan
[[1.01292026e+308]
 [            inf]
 [            nan]]
[[ 2.33597992]
 [-4.57759454]
 [ 3.76427382]]


C:\Users\nota0\AppData\Local\Temp\ipykernel_91600\4062790264.py:26: RuntimeWarning: overflow encountered in square
  while (np.sqrt(abs(np.sum((x_last - x)**2))) > eps):


# Метод Ньютона

## Зададим функцию

In [7]:
def F(x):
    ans = np.array([[0.0], [0.0], [0.0]])
    
    ans[0][0] = np.sin(x[1][0] - 1)
    
    ans[1][0] = x[2][0]**2 - 1
    
    ans[2][0] = x[0][0] - 1
    
    return ans

ans = F(np.array([[1], [1], [2]]))
print(np.sin(np.sqrt(ans[0][0])))
ans


0.0


array([[0.],
       [3.],
       [0.]])

## Зададим матрицу частных производных

In [8]:
def dF(x):
    ans = np.zeros((3, 3))
    
    x_n = x.T
 
    ans[0][1] = np.cos(x[1][0] - 1)

    ans[1][2] = 2*x[2][0]    
    
    ans[2][0] = 1 
    
    return ans

ans = dF(np.array([[1], [1], [2]]))
ans

array([[0., 1., 0.],
       [0., 0., 4.],
       [1., 0., 0.]])

## Теперь метод Ньютона

In [9]:
def Newton (F, dF, x_0, eps):
    x = np.copy(x_0)
    dx = np.ones((3,1))
    
    while np.sqrt(np.sum(dx**2)) > eps: 
        dx = np.linalg.inv(dF(x)).dot(-F(x))
        #print(dx)
    
        x += dx
        
    return x

In [10]:
ans = Newton(F, dF, c*np.random.rand(3, 1), 0.0001)
print(ans)

[[ 1.        ]
 [10.42477796]
 [ 1.        ]]
