In [3]:
import numpy as np
import math
import matplotlib.pyplot as plt
import random

Генератор $A$ и $x$ и $f$

In [6]:
n = 2
c = 10
A = c*np.random.rand(n, n)

x = c*np.random.rand(n, 1)

f = A.dot(x)

print(np.sqrt(np.sum((A.dot(x) - f)**2)))

print(A)
print(x)

print(f)

0.0
[[2.25652418 3.25340607]
 [3.53375741 9.86666261]]
[[6.26103083]
 [8.66079763]]
[[ 42.30525898]
 [107.57813215]]


Метод Якоби

In [7]:
def Iacoby (A, f, x_0, eps):
    x = x_0
    n = np.shape(A)[0]
    
    new_A = np.copy(A)
    new_f = np.copy(f)
    for i in range(n):
        new_f[i] = (f[i])/(A[i][i])
        new_A[i] = (A[i])/(A[i][i])

    new_A -= np.eye(n,n)
    
    #for i in range(100):
    while (np.sqrt(abs(np.sum((A.dot(x) - f)*(A.dot(x) - f)))) > eps):
            #print(np.sqrt(np.sum((A.dot(x) - f)**2)))
            x = new_f - new_A.dot(x)
    return x

In [8]:
x_ans = Iacoby(A, f, c*np.random.rand(n, 1), 0.001)
#x_ans = Iacoby(A, f, x, 0.001)
print(np.sqrt(np.sum((A.dot(x) - f)**2)))
print(np.sqrt(np.sum((A.dot(x_ans) - f)**2)))

print(x_ans)
#print(A.dot(x_ans))
print(x)
#print(A.dot(x))

0.0
0.0007594526864090197
[[6.26038382]
 [8.66101632]]
[[6.26103083]
 [8.66079763]]


Метод зейделя

In [49]:
def Seidel (A, f, x_0, eps):
    x_last = np.copy(x_0)
    x_last[0] = x_last[0] + 2*eps
    x = np.copy(x_0);
    
    n = np.shape(A)[0]
    
    new_A = np.copy(A)
    new_f = np.copy(f)
    for i in range(n):
        new_f[i] = (f[i])/(A[i][i])
        new_A[i] = (A[i])/(A[i][i])

    new_A -= np.eye(n,n)
        
    
    while (np.sqrt(abs(np.sum((x_last - x)**2))) > eps):
        x_last = np.copy(x)
        for i in range(n):
            x[i] = (new_f[i] - new_A[i].dot(x))
        
    return x
        

In [50]:
x_ans = Seidel(A, f, c*np.random.rand(n, 1), 0.001)
#x_ans = Iacoby(A, f, x, 0.001)
print(np.sqrt(np.sum((A.dot(x) - f)**2)))
print(np.sqrt(np.sum((A.dot(x_ans) - f)**2)))

print(x_ans)
#print(A.dot(x_ans))
print(x)
#print(A.dot(x))

0.0
0.0005970472318921338
[[6.26157792]
 [8.66060168]]
[[6.26103083]
 [8.66079763]]
