In [5]:
import numpy as np
import math
import matplotlib.pyplot as plt
import random


Генератор $A$ и $x$ и $f$

In [41]:
n = 3
c = 10

A = c*(np.random.rand(n, n) - 0.5*(np.ones((n,n))))
#A = np.zeros((3,3))
#A[0][1] = 1
#A[1][2] = 4
#A[2][0] = 1

x = c*(np.random.rand(n, 1) - 0.5*(np.ones((n,1))))

#x = np.ones((3,1))

f = A.dot(x)
#f = np.zeros((3, 1))
#f[1][0] = 3

#print(np.sqrt(np.sum((A.dot(x) - f)**2)))

print(A)
print(np.linalg.det(A))
print(x)

print(f)

print("x =", np.linalg.inv(A).dot(f))

[[-4.96015098  3.76172565  2.23498489]
 [ 0.60592025  4.49775368 -1.67636667]
 [ 2.90907598 -1.77075882 -1.46856882]]
0.8483689392134435
[[ 4.09410105]
 [ 2.18769388]
 [-1.59687306]]
[[-15.64684233]
 [ 14.99735174]
 [ 10.38129077]]
x = [[ 4.09410105]
 [ 2.18769388]
 [-1.59687306]]


Метод Якоби

In [39]:
def Iacoby (A, f, x_0, eps):
    x = np.copy(x_0)
    n = np.shape(A)[0]
    
    new_A = np.copy(A)
    new_f = np.copy(f)
    
    print(A)
    
    for i in range(n):
        new_f[i] = new_f[i]/new_A[i][i]
        new_A[i] = new_A[i]/new_A[i][i]

    #print(new_A)
    #print(np.linalg.det(new_A))
    #print(new_f)
    
    q = abs(np.linalg.det(new_A))
    print(q)
    if q >= 1:
        print("bad q")
        return 0
    
    if q <= 1/2:
        q = 1/2
        
    new_A -= np.eye(n,n)
    
    
    print(new_A)
    #print(A)
    
    last_x = np.copy(x)
    last_x[0][0] = last_x[0][0] + 2*eps
    
    #for i in range(100):
    while (np.sqrt(abs(np.sum((x - last_x)**2))) > (1 - q)*eps/q):
            #print(np.sqrt(np.sum((A.dot(x) - f)**2)))
            last_x = x
            x = new_f - new_A.dot(x)
            #print(x)
    return x

In [42]:
x_ans = Iacoby(A, f, c*np.random.rand(n, 1), 0.001)
#x_ans = Iacoby(A, f, x, 0.001)
#print(np.sqrt(np.sum((A.dot(x) - f)**2)))
#print(np.sqrt(np.sum((A.dot(x_ans) - f)**2)))

print(x_ans)
#print(A.dot(x_ans))
print(x)
#print(A.dot(x))

[[-4.96015098  3.76172565  2.23498489]
 [ 0.60592025  4.49775368 -1.67636667]
 [ 2.90907598 -1.77075882 -1.46856882]]
0.025894044645377194
[[ 0.         -0.75838934 -0.45058808]
 [ 0.13471619  0.         -0.37271198]
 [-1.98089183  1.20577177  0.        ]]
[[ 4.14874623]
 [ 2.21081276]
 [-1.51570366]]
[[ 4.09410105]
 [ 2.18769388]
 [-1.59687306]]


Метод зейделя

In [43]:
def Seidel (A, f, x_0, eps):
    x_last = np.copy(x_0)
    x_last[0] = x_last[0] + 2*eps
    x = np.copy(x_0);
    
    n = np.shape(A)[0]
    
    new_A = np.copy(A)
    new_f = np.copy(f)
    
    for i in range(n): 
        if new_A[i][i] == 0:
            for j in range(n):
                if A[j][i] != 0:
                    new_A[i] += A[j]
                    new_f[i] += f[j]
                    break
    
    for i in range(n):
        new_f[i] /= new_A[i][i]
        new_A[i] /= new_A[i][i]

    new_A -= np.eye(n,n)
        
    
    while (np.sqrt(abs(np.sum((x_last - x)**2))) > eps):
        x_last = np.copy(x)
        for i in range(n):
            x[i] = (new_f[i] - new_A[i].dot(x))
        
    return x
        

In [44]:
x_ans = Seidel(A, f, c*np.random.rand(n, 1), 0.001)
#x_ans = Iacoby(A, f, x, 0.001)
print(np.sqrt(np.sum((A.dot(x) - f)**2)))
print(np.sqrt(np.sum((A.dot(x_ans) - f)**2)))

print(x_ans)
#print(A.dot(x_ans))
print(x)
#print(A.dot(x))

0.0
0.0029690651143240107
[[ 4.12647654]
 [ 2.20138171]
 [-1.54924511]]
[[ 4.09410105]
 [ 2.18769388]
 [-1.59687306]]


# Метод Ньютона

## Зададим функцию

In [7]:
def F(x):
    ans = np.array([[0.0], [0.0], [0.0]])
    
    ans[0][0] = np.sin(x[1][0] - 1)
    
    ans[1][0] = x[2][0]**2 - 1
    
    ans[2][0] = x[0][0] - 1
    
    return ans

ans = F(np.array([[1], [1], [2]]))
print(np.sin(np.sqrt(ans[0][0])))
ans


0.0


array([[0.],
       [3.],
       [0.]])

## Зададим матрицу частных производных

In [8]:
def dF(x):
    ans = np.zeros((3, 3))
    
    x_n = x.T
 
    ans[0][1] = np.cos(x[1][0] - 1)

    ans[1][2] = 2*x[2][0]    
    
    ans[2][0] = 1 
    
    return ans

ans = dF(np.array([[1], [1], [2]]))
ans

array([[0., 1., 0.],
       [0., 0., 4.],
       [1., 0., 0.]])

## Теперь метод Ньютона

In [9]:
def Newton (F, dF, x_0, eps):
    x = np.copy(x_0)
    dx = np.ones((3,1))
    
    while np.sqrt(np.sum(dx**2)) > eps: 
        dx = np.linalg.inv(dF(x)).dot(-F(x))
        #print(dx)
    
        x += dx
        
    return x

In [10]:
ans = Newton(F, dF, c*np.random.rand(3, 1), 0.0001)
print(ans)

[[ 1.        ]
 [10.42477796]
 [ 1.        ]]
