In [1]:
import numpy as np
import math
import matplotlib.pyplot as plt
import random


Генератор $A$ и $x$ и $f$

In [19]:
n = 3
c = 10

A = c*(np.random.rand(n, n) - 0.5*(np.ones((n,n))))
#A = np.zeros((3,3))
#A[0][1] = 1
#A[1][2] = 4
#A[2][0] = 1

x = c*(np.random.rand(n, 1) - 0.5*(np.ones((n,1))))

#x = np.ones((3,1))

f = A.dot(x)
#f = np.zeros((3, 1))
#f[1][0] = 3

#print(np.sqrt(np.sum((A.dot(x) - f)**2)))

print(A)
print(x)

print(f)

[[ 1.71798168  3.43606162 -4.77968251]
 [-0.49171076  2.97030217 -1.78136361]
 [ 2.40869078  2.73492981 -2.99557768]]
[[ 1.77343377]
 [-1.87927881]
 [-3.82725838]]
[[14.88248889]
 [ 0.36369644]
 [10.5968077 ]]


Метод Якоби

In [20]:
def Iacoby (A, f, x_0, eps):
    x = np.copy(x_0)
    n = np.shape(A)[0]
    
    new_A = np.copy(A)
    new_f = np.copy(f)
    
    for i in range(n):
        new_f[i] = new_f[i]/new_A[i][i]
        new_A[i] = new_A[i]/new_A[i][i]

    print(new_A)
    print(new_f)
        
    new_A -= np.eye(n,n)
    
    
    print(new_A)
    #print(A)
    
    for i in range(100):
    #while (np.sqrt(abs(np.sum((A.dot(x) - f)**2))) > eps):
            #print(np.sqrt(np.sum((A.dot(x) - f)**2)))
            old_x = np.copy(x)
            x = new_f - new_A.dot(old_x)
            #print(x)
    return x

In [21]:
x_ans = Iacoby(A, f, c*np.random.rand(n, 1), 0.001)
#x_ans = Iacoby(A, f, x, 0.001)
#print(np.sqrt(np.sum((A.dot(x) - f)**2)))
#print(np.sqrt(np.sum((A.dot(x_ans) - f)**2)))

print(x_ans)
#print(A.dot(x_ans))
print(x)
#print(A.dot(x))

[[ 1.          2.00005719 -2.78214987]
 [-0.16554234  1.         -0.59972471]
 [-0.80408223 -0.91298911  1.        ]]
[[ 8.66277506]
 [ 0.12244426]
 [-3.53748387]]
[[ 0.          2.00005719 -2.78214987]
 [-0.16554234  0.         -0.59972471]
 [-0.80408223 -0.91298911  0.        ]]
[[ 1.95301968e+22]
 [ 1.80428084e+21]
 [-1.04068382e+22]]
[[ 1.77343377]
 [-1.87927881]
 [-3.82725838]]


Метод зейделя

In [5]:
def Seidel (A, f, x_0, eps):
    x_last = np.copy(x_0)
    x_last[0] = x_last[0] + 2*eps
    x = np.copy(x_0);
    
    n = np.shape(A)[0]
    
    new_A = np.copy(A)
    new_f = np.copy(f)
    
    for i in range(n): 
        if new_A[i][i] == 0:
            for j in range(n):
                if A[j][i] != 0:
                    new_A[i] += A[j]
                    new_f[i] += f[j]
                    break
    
    for i in range(n):
        new_f[i] /= new_A[i][i]
        new_A[i] /= new_A[i][i]

    new_A -= np.eye(n,n)
        
    
    while (np.sqrt(abs(np.sum((x_last - x)**2))) > eps):
        x_last = np.copy(x)
        for i in range(n):
            x[i] = (new_f[i] - new_A[i].dot(x))
        
    return x
        

In [6]:
x_ans = Seidel(A, f, c*np.random.rand(n, 1), 0.001)
#x_ans = Iacoby(A, f, x, 0.001)
print(np.sqrt(np.sum((A.dot(x) - f)**2)))
print(np.sqrt(np.sum((A.dot(x_ans) - f)**2)))

print(x_ans)
#print(A.dot(x_ans))
print(x)
#print(A.dot(x))

0.0
nan
[[inf]
 [nan]
 [nan]]
[[ 1.43509642e+00]
 [-4.66775277e+00]
 [ 3.50351484e-03]]


C:\Users\nota0\AppData\Local\Temp\ipykernel_56824\4062790264.py:26: RuntimeWarning: overflow encountered in square
  while (np.sqrt(abs(np.sum((x_last - x)**2))) > eps):
C:\Users\nota0\AppData\Local\Temp\ipykernel_56824\4062790264.py:26: RuntimeWarning: overflow encountered in subtract
  while (np.sqrt(abs(np.sum((x_last - x)**2))) > eps):


# Метод Ньютона

## Зададим функцию

In [7]:
def F(x):
    ans = np.array([[0.0], [0.0], [0.0]])
    
    ans[0][0] = np.sin(x[1][0] - 1)
    
    ans[1][0] = x[2][0]**2 - 1
    
    ans[2][0] = x[0][0] - 1
    
    return ans

ans = F(np.array([[1], [1], [2]]))
print(np.sin(np.sqrt(ans[0][0])))
ans


0.0


array([[0.],
       [3.],
       [0.]])

## Зададим матрицу частных производных

In [8]:
def dF(x):
    ans = np.zeros((3, 3))
    
    x_n = x.T
 
    ans[0][1] = np.cos(x[1][0] - 1)

    ans[1][2] = 2*x[2][0]    
    
    ans[2][0] = 1 
    
    return ans

ans = dF(np.array([[1], [1], [2]]))
ans

array([[0., 1., 0.],
       [0., 0., 4.],
       [1., 0., 0.]])

## Теперь метод Ньютона

In [9]:
def Newton (F, dF, x_0, eps):
    x = np.copy(x_0)
    dx = np.ones((3,1))
    
    while np.sqrt(np.sum(dx**2)) > eps: 
        dx = np.linalg.inv(dF(x)).dot(-F(x))
        #print(dx)
    
        x += dx
        
    return x

In [10]:
ans = Newton(F, dF, c*np.random.rand(3, 1), 0.0001)
print(ans)

[[1.]
 [1.]
 [1.]]
