In [1]:
import numpy as np
import math
import matplotlib.pyplot as plt
import random

Генератор $A$ и $x$ и $f$

In [120]:
n = 2
C = 10
A = С*np.random.rand(n, n)

x = C*np.random.rand(n, 1)

f = A.dot(x)

print(np.sqrt(np.sum((A.dot(x) - f)**2)))

print(A)
print(x)

print(f)

0.0
[[4.81781078 0.68017526]
 [6.18184556 8.94534901]]
[[9.10796015]
 [7.81106282]]
[[ 49.19332031]
 [126.1766861 ]]


Метод Якоби

In [160]:
def Iacoby (A, f, x_0, eps):
    x = x_0
    n = np.shape(A)[0]
    
    new_A = np.copy(A)
    new_f = np.copy(f)
    for i in range(n):
        new_f[i] = (f[i])/(A[i][i])
        new_A[i] = (A[i])/(A[i][i])

    new_A -= np.eye(n,n)
    
    #for i in range(100):
    while (np.sqrt(abs(np.sum((A.dot(x) - f)*(A.dot(x) - f)))) > eps):
            #print(np.sqrt(np.sum((A.dot(x) - f)**2)))
            x = new_f - new_A.dot(x)
    return x

In [162]:
x_ans = Iacoby(A, f, C*np.random.rand(n, 1), 0.001)
#x_ans = Iacoby(A, f, x, 0.001)
print(np.sqrt(np.sum((A.dot(x) - f)**2)))
print(np.sqrt(np.sum((A.dot(x_ans) - f)**2)))

print(x_ans)
#print(A.dot(x_ans))
print(x)
#print(A.dot(x))

0.0
0.00048572287395854503
[[9.1078813 ]
 [7.81108174]]
[[9.10796015]
 [7.81106282]]
